TableOfContents = false
baseurl = "https://athiangames.com/"
buildFuture = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
languageCode = "en-us"
metaDataFormat = "yaml"
paginate = 9
summaryLength = 5
theme = "athian_games_theme"
title = "Athian Games"
[[menu.main]]
name = "Courses"
weight = 3
[[menu.main]]
identifier = "products"
name = "Products"
url = "/product/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true
[minify.tdewolff.css]
decimals = -1
keepCSS2 = true
[minify.tdewolff.html]
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = true
keepWhitespace = false
[minify.tdewolff.js]
[minify.tdewolff.json]
[minify.tdewolff.svg]
decimals = -1
[minify.tdewolff.xml]
keepWhitespace = false
[params]
enableLozad = true
legalname = "Athian Games OPC Pvt Ltd."
copyright = "Copyright © 2023, Athian Games OPC Pvt Ltd. All right reserved."
socialYouTube = "https://www.youtube.com/channel/UCfDyVAjpn6eOyNbg9iQ7C_w"
socialFacebook = "https://www.facebook.com/Athianoir/"
socialLinkedIn = "https://in.linkedin.com/company/athiangames?trk=public_profile_experience-item_profile-section-card_subtitle-click"
    
[taxonomies]
category = "categories"
product_category = "product_categories"
course_category = "course_categories"
tag = "tags"
