[build]
  command = "npm run build"
  install = "corepack disable && npm install --legacy-peer-deps"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "20"
