---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: directory
  path: content/home-slider
  label: Home slider
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - home-slider
- type: document
  path: content/_index.md
  label: Home Page
- type: heading
  label: Primary Sections
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - blog
- type: directory
  path: content/testimonials
  label: Testimonials
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - testimonials
- type: heading
  label: Work
- type: heading
  label: Other Sections
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: document
  path: content/about/_index.md
  label: About
- type: document
  path: content/privacy-policy/_index.md
  label: Privacy Policy
- type: document
  path: content/terms-conditions/_index.md
  label: Terms & Conditions
- type: heading
  label: Website Meta/Data
- type: directory
  path: content/scripts
  label: Scripts
  create: all
  match: "**/*"
  templates:
  - scripts
- type: document
  path: content/info/_index.md
  label: Site Info
- type: heading
  label: Not Editable
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
  templates:
  - index
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.56.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.56.3
