---
label: Product
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: title
  label: title
- name: topText
  type: text
  config:
    required: false
  label: topText
  description: Baner tittle
- type: text
  name: summary
  label: summary
- type: list
  name: product_categories
  label: product_categories
- name: image
  type: file
  config:
    maxSize: 64
  label: image
  default: "/images/minimapcover.png"
- type: field_group_list
  name: buttons
  label: buttons
  fields:
  - type: text
    name: buttonText
    label: buttonText
  - type: textarea
    name: buttonLink
    label: buttonLink
- type: text
  name: seotitle
  label: seotitle
- type: text
  name: seodescription
  label: seodescription
- type: boolean
  name: private
  label: private
- type: text
  name: canonical
  label: canonical
- type: file
  name: bannerImage
  label: bannerImage
  default: "/images/minimapcover.png"
- type: text
  name: contentVideoId
  label: contentVideoId
- name: contentVideoThumbnail
  type: file
  config:
    maxSize: 64
  label: contentVideoThumbnail
- type: field_group_list
  name: features
  label: features
  fields:
  - type: file
    name: image
    label: image
    default: "/images/minimapcover.png"
  - type: text
    name: title
    label: title
  - type: textarea
    name: description
    label: description
  - type: field_group_list
    name: buttons
    label: buttons
    fields:
    - type: text
      name: buttonText
      label: buttonText
    - type: text
      name: buttonLink
      label: buttonLink
- type: textarea
  name: description
  label: description
- name: bottomText
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: bottomText
  description: Text defined below banner title
- name: fontFamily
  type: text
  config:
    required: false
  label: fontFamily
- name: contentFontSize
  type: text
  config:
    required: false
  label: contentFontSize
  description: 'Example: "16px", "1rem"'
  default: '24'
- name: featureTitleFontSize
  type: text
  config:
    required: false
  label: featureTitleFontSize
  description: Example "16px", "1rem"
  default: '24'
- name: featureTextFontSize
  type: text
  config:
    required: false
  label: featureTextFontSize
  description: Example "16px", "1rem"
  default: '18'
pages:
- content/product/minimap-map-and-navigation-system.md
- content/product/niagara-curves-and-surfaces.md
- content/product/procedural-vortex-tunnel.md
